language: generic
root: linux
services:
    - docker


before_install:
    - docker build -t 7immyh/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true 7immyh/docker-react npm run test

deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    edge: true
    app: docker-react-th
    on:
        branch: master
    